{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{instance=\"localhost:8080\", job=\"prometheus\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{instance=\"localhost:8080\", job=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_private_memory_bytes{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VnExpress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vnexpress_requests_failure{instance=\"localhost:8080\", job=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vnexpress_requests_total{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vnexpress_requests_success{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TuoiTre",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tuoitre_requests_total{instance=\"localhost:8080\", job=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "tuoitre_requests_success{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "tuoitre_requests_failure{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VnExpress Response time (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(vnexpress_request_duration_seconds_count{instance=\"localhost:8080\"}[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TuoiTre Response time (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(tuoitre_request_duration_seconds_sum{instance=\"localhost:8080\"}[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}